export * from './c3-cleaning_code'
export * from './c4-popular_composition'
export * from './c5-writing_code_for_the_browser'
export * from './c7-antipatters_to_be_avoided'
export * from './c8-react_hooks'
export * from './c9-react_router'
export * from './c10-react_18_new_features'
export * from './c11-managing_data'
export * from "./c12-server-side_rendering"
